# Generated by Django 4.0.3 on 2022-04-01 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supermarket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(max_length=30)),
                ('order_date', models.DateField()),
                ('ship_date', models.DateField()),
                ('ship_mode', models.CharField(max_length=30)),
                ('customer_id', models.CharField(max_length=20)),
                ('customer_name', models.CharField(max_length=50)),
                ('segment', models.CharField(max_length=30)),
                ('country', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('state', models.CharField(max_length=30)),
                ('postal_code', models.IntegerField()),
                ('region', models.CharField(max_length=30)),
                ('product_id', models.CharField(max_length=30)),
                ('category', models.CharField(max_length=50)),
                ('product_name', models.CharField(max_length=200)),
                ('sales', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('discount', models.IntegerField()),
                ('profit', models.FloatField()),
            ],
        ),
    ]
